#application name for our service
spring.application.name=auth-service

#port on which our service should run
server.port=8081

#configure Spring Boot Actuator to control which operational endpoints are accessible over HTTP
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


#After adding the dependency in pom.xml for postgreSql driver, spring data JPA. we need to give the database connection url and properties. Otherwise we will get error in maven clean install.
spring.datasource.url=jdbc:postgresql://localhost:5432/riya_boutique
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

############################################
# LOGGING CONFIGURATION

#To create the logger file in root directory of project - All logs will automatically save in this file in additional terminal/console
logging.file.name=R:/riya-boutique-fashion/backend/riya-boutique-parent/auth-service/logs/riya-boutique.log

#To set the log level [ERROR>WARN>INFO>DEBUG>TRACE] : As you move right, you will get all logs details in left's to that. Error displaying the least, TRACE being the most or maximum details. Bydefault Log level is INFO.
logging.level.root=INFO

#To keep the Logging level to ERROR> logging.level.root=DEBUG
#To keep the Logging level to WARN> logging.level.root=DEBUG
#To keep the Logging level to INFO> logging.level.root=DEBUG
#To keep the Logging level to DEBUG> logging.level.root=DEBUG
#To keep the Logging level to TRACE> logging.level.root=TRACE

#Most Important : Log Rotation Property.
#Whenever the log file reached a particular size limit (say 10mb), a new log file will create. And, when log file creation date is about to exceed a value (say 30 days) i.e, getting old. So, the older log file get delete
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

#Different logging levels for different packages, hibernate, spring
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.riyaboutique.auth=DEBUG

#Customize the logging line in a format > for console/terminal output
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

#Customize the logging line in a format > for saving in log file
logging.pattern.file=%d %-5level [%thread] %logger - %msg%n

