#application name for our service
spring.application.name=auth-service

#port on which our service should run
server.port=8081

#configure Spring Boot Actuator to control which operational endpoints are accessible over HTTP
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


