#application name for our service
spring.application.name=auth-service

#port on which our service should run
server.port=8081

#configure Spring Boot Actuator to control which operational endpoints are accessible over HTTP
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


#After adding the dependency in pom.xml for postgreSql driver, spring data JPA. we need to give the database connection url and properties. Otherwise we will get error in maven clean install.
spring.datasource.url=jdbc:postgresql://localhost:5432/riya_boutique
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true